In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
from pandas import DataFrame as df
from pandas import Series
import seaborn as sns
import matplotlib.pyplot as plt 
import scipy.stats as sp
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
import sys
rc('font', family=font_name)
%matplotlib inline

In [2]:
healthdata2014 = pd.read_csv(r"C:\Users\digus\Desktop\db금융공모전\건강검진데이터\건강검진정보_2014.csv", delimiter=',', engine="python")
healthdata2015 = pd.read_csv(r"C:\Users\digus\Desktop\db금융공모전\건강검진데이터\건강검진정보_2015.csv", delimiter=',', engine="python")
healthdata2016 = pd.read_csv(r"C:\Users\digus\Desktop\db금융공모전\건강검진데이터\건강검진정보_2016.csv", delimiter=',', engine="python")
healthdata2017 = pd.read_csv(r"C:\Users\digus\Desktop\db금융공모전\건강검진데이터\건강검진정보_2017.csv", delimiter=',', engine="python")
healthdata2018 = pd.read_csv(r"C:\Users\digus\Desktop\db금융공모전\건강검진데이터\건강검진정보_2018.csv", delimiter=',', engine="python")

In [3]:
healthdata2014 = healthdata2014.dropna(axis=0, how='any')

In [4]:
healthdata2014 = healthdata2014.drop(['기준년도','가입자일련번호', '시도코드', '신장(5Cm단위)' ,'체중(5Kg단위)','시력(좌)', '시력(우)',
                                      '청력(좌)', '청력(우)', '구강검진 수검여부', '치아우식증유무',
                                      '치석유무', '데이터 기준일자'], axis=1)

In [5]:
healthdata2015 = healthdata2015.dropna(axis=0, how='any')

In [6]:
healthdata2015 = healthdata2015.drop(['기준년도','가입자일련번호', '시도코드', '신장(5Cm단위)' ,'체중(5Kg단위)', '시력(좌)', '시력(우)',
                                      '청력(좌)', '청력(우)', '구강검진 수검여부', '치아우식증유무',
                                      '치석유무', '데이터 기준일자'], axis=1)

In [7]:
healthdata2016 = healthdata2016.dropna(axis=0, how='any')

In [8]:
healthdata2016 = healthdata2016.drop(['기준년도','가입자일련번호', '시도코드', '신장(5Cm단위)' ,'체중(5Kg단위)', '시력(좌)', '시력(우)',
                                      '청력(좌)', '청력(우)', '구강검진 수검여부', '치아우식증유무', '결손치유무',
                                      '치석', '치아마모증유무', '제3대구치(사랑니)이상','데이터공개일자'], axis=1)

In [9]:
healthdata2017 = healthdata2017.dropna(axis=0, how='any')

In [10]:
healthdata2017 = healthdata2017.drop(['기준년도','가입자일련번호', '시도코드', '신장(5Cm단위)' ,'체중(5Kg단위)', '시력(좌)', '시력(우)',
                                      '청력(좌)', '청력(우)', '구강검진 수검여부', '치아우식증유무', '결손치유무',
                                      '치석', '치아마모증유무', '제3대구치(사랑니)이상','데이터공개일자'], axis=1)

In [11]:
healthdata2018 = healthdata2018.dropna(axis=0, how='any')

In [12]:
healthdata2018 = healthdata2018.drop(['기준년도','가입자일련번호','신장(5Cm단위)' ,'체중(5Kg단위)', '시도코드', '시력(좌)', '시력(우)',
                                      '청력(좌)', '청력(우)', '구강검진수검여부', '치아우식증유무', '결손치유무',
                                      '치석', '치아마모증유무', '제3대구치(사랑니)이상','데이터공개일자'], axis=1)

In [13]:
healthdataAll = pd.concat([healthdata2014, healthdata2015, healthdata2016, healthdata2017, healthdata2018])

In [14]:
manAlldata = healthdataAll[healthdataAll['성별코드'] == 1]

In [15]:
womanAlldata = healthdataAll[healthdataAll['성별코드'] == 2]

In [16]:
i1 = manAlldata[manAlldata['연령대코드(5세단위)'] <= 2].index
manAlldata = manAlldata.drop(i1)

In [17]:
i2 = womanAlldata[womanAlldata['연령대코드(5세단위)'] <= 3].index
womanAlldata = womanAlldata.drop(i2)

In [18]:
manAlldata

,성별코드,연령대코드(5세단위),BMI,허리둘레,수축기혈압,이완기혈압,식전혈당(공복혈당),총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부
0,1,6,23.1,79.0,110.0,70.0,84.0,203.0,315.0,44.0,96.0,15.9,1.0,1.2,31.0,18.0,23.0,3.0,0.0
2,1,12,24.2,95.0,145.0,91.0,284.0,166.0,82.0,41.0,109.0,11.5,3.0,0.6,138.0,73.0,112.0,3.0,1.0
84,1,11,17.3,78.0,115.0,74.0,91.0,188.0,102.0,63.0,104.0,11.6,1.0,0.9,18.0,7.0,14.0,2.0,1.0
126,1,6,23.5,89.0,135.0,80.0,98.0,168.0,51.0,73.0,84.0,14.8,1.0,0.9,20.0,9.0,17.0,1.0,0.0
304,1,15,23.9,76.0,143.0,98.0,89.0,174.0,98.0,42.0,112.0,13.9,1.0,1.0,18.0,11.0,9.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999978,1,7,20.8,76.0,110.0,70.0,87.0,151.0,82.0,50.0,84.0,15.9,1.0,1.0,23.0,16.0,13.0,3.0,1.0
999990,1,7,27.3,88.0,105.0,61.0,85.0,236.0,210.0,31.0,163.0,14.6,1.0,1.0,46.0,99.0,58.0,2.0,1.0
999993,1,5,26.2,95.0,120.0,80.0,91.0,196.0,133.0,54.0,115.0,16.1,1.0,1.0,23.0,26.0,35.0,3.0,1.0
999994,1,6,25.7,82.0,135.0,80.0,114.0,142.0,62.0,57.0,73.0,15.3,1.0,1.2,20.0,18.0,39.0,3.0,1.0
999996,1,7,19.6,73.0,110.0,65.0,86.0,174.0,70.0,65.0,95.0,15.7,1.0,0.9,20.0,11.0,14.0,1.0,1.0

In [19]:
manAlldata = manAlldata[manAlldata["연령대코드(5세단위)"]<=14]

In [20]:
womanAlldata = womanAlldata[womanAlldata["연령대코드(5세단위)"]<=14]

In [21]:
womanAlldata

,성별코드,연령대코드(5세단위),BMI,허리둘레,수축기혈압,이완기혈압,식전혈당(공복혈당),총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부
3,2,11,29.4,104.0,158.0,100.0,87.0,267.0,148.0,48.0,189.0,13.5,1.0,0.9,19.0,14.0,21.0,1.0,0.0
16,2,6,14.7,59.0,98.0,64.0,70.0,143.0,86.0,51.0,74.0,13.7,1.0,0.9,20.0,15.0,40.0,1.0,1.0
73,2,11,31.2,91.0,104.0,62.0,119.0,221.0,64.0,56.0,152.0,11.0,1.0,0.8,23.0,15.0,22.0,1.0,1.0
148,2,7,25.0,78.0,110.0,70.0,99.0,217.0,52.0,84.0,123.0,13.9,1.0,0.7,19.0,17.0,13.0,1.0,1.0
186,2,7,20.8,64.0,110.0,60.0,93.0,174.0,73.0,85.0,74.0,10.9,1.0,0.8,20.0,15.0,14.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999933,2,5,25.7,75.0,120.0,80.0,90.0,155.0,63.0,57.0,85.0,12.7,1.0,0.7,23.0,21.0,21.0,1.0,1.0
999963,2,5,20.2,65.0,110.0,72.0,81.0,158.0,40.0,83.0,58.0,13.6,1.0,0.9,21.0,13.0,16.0,1.0,0.0
999968,2,9,22.9,68.0,110.0,70.0,89.0,125.0,72.0,36.0,74.0,12.6,1.0,0.8,23.0,24.0,21.0,1.0,1.0
999972,2,11,20.8,79.0,130.0,85.0,81.0,212.0,84.0,73.0,122.0,12.6,1.0,0.5,25.0,15.0,13.0,1.0,1.0
999974,2,13,20.2,76.0,144.0,98.0,92.0,156.0,46.0,38.0,109.0,13.1,1.0,0.7,19.0,17.0,23.0,1.0,1.0

In [22]:
m = manAlldata.drop("연령대코드(5세단위)", axis=1)

In [23]:
m

,성별코드,BMI,허리둘레,수축기혈압,이완기혈압,식전혈당(공복혈당),총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부
0,1,23.1,79.0,110.0,70.0,84.0,203.0,315.0,44.0,96.0,15.9,1.0,1.2,31.0,18.0,23.0,3.0,0.0
2,1,24.2,95.0,145.0,91.0,284.0,166.0,82.0,41.0,109.0,11.5,3.0,0.6,138.0,73.0,112.0,3.0,1.0
84,1,17.3,78.0,115.0,74.0,91.0,188.0,102.0,63.0,104.0,11.6,1.0,0.9,18.0,7.0,14.0,2.0,1.0
126,1,23.5,89.0,135.0,80.0,98.0,168.0,51.0,73.0,84.0,14.8,1.0,0.9,20.0,9.0,17.0,1.0,0.0
440,1,20.1,75.0,117.0,68.0,85.0,182.0,132.0,43.0,113.0,15.4,1.0,1.1,28.0,21.0,26.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999978,1,20.8,76.0,110.0,70.0,87.0,151.0,82.0,50.0,84.0,15.9,1.0,1.0,23.0,16.0,13.0,3.0,1.0
999990,1,27.3,88.0,105.0,61.0,85.0,236.0,210.0,31.0,163.0,14.6,1.0,1.0,46.0,99.0,58.0,2.0,1.0
999993,1,26.2,95.0,120.0,80.0,91.0,196.0,133.0,54.0,115.0,16.1,1.0,1.0,23.0,26.0,35.0,3.0,1.0
999994,1,25.7,82.0,135.0,80.0,114.0,142.0,62.0,57.0,73.0,15.3,1.0,1.2,20.0,18.0,39.0,3.0,1.0
999996,1,19.6,73.0,110.0,65.0,86.0,174.0,70.0,65.0,95.0,15.7,1.0,0.9,20.0,11.0,14.0,1.0,1.0

In [24]:
w = womanAlldata.drop("연령대코드(5세단위)", axis=1)

In [25]:
w

,성별코드,BMI,허리둘레,수축기혈압,이완기혈압,식전혈당(공복혈당),총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부
3,2,29.4,104.0,158.0,100.0,87.0,267.0,148.0,48.0,189.0,13.5,1.0,0.9,19.0,14.0,21.0,1.0,0.0
16,2,14.7,59.0,98.0,64.0,70.0,143.0,86.0,51.0,74.0,13.7,1.0,0.9,20.0,15.0,40.0,1.0,1.0
73,2,31.2,91.0,104.0,62.0,119.0,221.0,64.0,56.0,152.0,11.0,1.0,0.8,23.0,15.0,22.0,1.0,1.0
148,2,25.0,78.0,110.0,70.0,99.0,217.0,52.0,84.0,123.0,13.9,1.0,0.7,19.0,17.0,13.0,1.0,1.0
186,2,20.8,64.0,110.0,60.0,93.0,174.0,73.0,85.0,74.0,10.9,1.0,0.8,20.0,15.0,14.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999933,2,25.7,75.0,120.0,80.0,90.0,155.0,63.0,57.0,85.0,12.7,1.0,0.7,23.0,21.0,21.0,1.0,1.0
999963,2,20.2,65.0,110.0,72.0,81.0,158.0,40.0,83.0,58.0,13.6,1.0,0.9,21.0,13.0,16.0,1.0,0.0
999968,2,22.9,68.0,110.0,70.0,89.0,125.0,72.0,36.0,74.0,12.6,1.0,0.8,23.0,24.0,21.0,1.0,1.0
999972,2,20.8,79.0,130.0,85.0,81.0,212.0,84.0,73.0,122.0,12.6,1.0,0.5,25.0,15.0,13.0,1.0,1.0
999974,2,20.2,76.0,144.0,98.0,92.0,156.0,46.0,38.0,109.0,13.1,1.0,0.7,19.0,17.0,23.0,1.0,1.0

In [26]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit_transform(m)
scaler.fit_transform(w)
feature = scaler.fit_transform(m)
feature2 = scaler.fit_transform(w)

In [27]:
def elbow(X):
    sse = []

    for i in range(1,20):
        km = KMeans(n_clusters=i,algorithm='auto', random_state=42)
        km.fit(X)
        sse.append(km.inertia_)

    plt.plot(range(1,20), sse, marker='o')
    plt.xlabel('K')
    plt.ylabel('SSE')
    plt.show()

In [ ]:
elbow()

In [28]:
k= 10

In [29]:
k2=10

In [30]:
kmean_cl = KMeans(n_clusters=k, algorithm='auto')
kmeans = kmean_cl.fit(feature)
km_predict = kmean_cl.predict(feature)
km_predict

array([9, 1, 7, ..., 1, 1, 3])

In [31]:
#np.savetxt("k=10예측", km_predict, delimiter=",")

In [32]:
km_predict = km_predict.tolist()

In [36]:
km_predict

[9,
 1,
 7,
 5,
 1,
 3,
 9,
 3,
 7,
 9,
 9,
 3,
 6,
 1,
 9,
 2,
 3,
 3,
 6,
 4,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 9,
 7,
 6,
 9,
 7,
 2,
 5,
 6,
 9,
 4,
 1,
 8,
 1,
 5,
 3,
 6,
 1,
 9,
 9,
 9,
 7,
 9,
 9,
 3,
 6,
 6,
 3,
 7,
 0,
 3,
 9,
 8,
 9,
 1,
 3,
 3,
 5,
 3,
 7,
 1,
 6,
 1,
 1,
 8,
 2,
 9,
 0,
 9,
 3,
 9,
 6,
 6,
 5,
 5,
 4,
 9,
 6,
 1,
 4,
 5,
 5,
 1,
 5,
 3,
 7,
 4,
 6,
 6,
 9,
 9,
 7,
 6,
 6,
 9,
 6,
 4,
 3,
 9,
 9,
 9,
 9,
 9,
 9,
 3,
 1,
 5,
 5,
 1,
 8,
 9,
 5,
 1,
 7,
 3,
 4,
 1,
 6,
 5,
 5,
 9,
 9,
 4,
 1,
 9,
 6,
 7,
 5,
 9,
 9,
 6,
 3,
 4,
 5,
 1,
 3,
 9,
 9,
 9,
 1,
 8,
 6,
 9,
 3,
 5,
 9,
 6,
 9,
 9,
 9,
 3,
 8,
 6,
 5,
 9,
 6,
 6,
 9,
 5,
 1,
 4,
 9,
 5,
 5,
 9,
 5,
 5,
 5,
 6,
 1,
 9,
 5,
 9,
 9,
 9,
 4,
 5,
 9,
 5,
 9,
 8,
 3,
 6,
 3,
 6,
 8,
 4,
 9,
 3,
 9,
 9,
 9,
 9,
 9,
 5,
 8,
 6,
 4,
 4,
 3,
 5,
 5,
 6,
 9,
 2,
 9,
 9,
 9,
 6,
 3,
 9,
 8,
 6,
 9,
 7,
 5,
 9,
 9,
 6,
 6,
 7,
 9,
 0,
 5,
 1,
 9,
 9,
 9,
 1,
 3,
 9,
 9,
 9,
 0,
 9,
 4,
 9,
 5,
 9,
 3,
 4,
 2,
 2,
 5,
 5,
 4,
 9,
 7,
 9,
 6,
 6,
 9,
 9,
 6,
 1,
 8,
 9,
 9,
 5,
 6,
 1,
 6,
 9,
 9,
 0,
 6,
 8,
 6,
 9,
 2,
 0,
 6,
 3,
 1,
 1,
 6,
 9,
 4,
 9,
 5,
 9,
 9,
 2,
 9,
 9,
 1,
 0,
 0,
 9,
 7,
 6,
 6,
 5,
 8,
 9,
 1,
 4,
 2,
 2,
 7,
 1,
 9,
 6,
 6,
 3,
 7,
 9,
 3,
 8,
 9,
 7,
 5,
 1,
 1,
 9,
 1,
 7,
 1,
 7,
 1,
 9,
 3,
 5,
 1,
 9,
 4,
 9,
 9,
 6,
 1,
 5,
 3,
 9,
 9,
 5,
 7,
 0,
 1,
 5,
 6,
 1,
 4,
 9,
 9,
 9,
 9,
 3,
 4,
 9,
 3,
 7,
 5,
 5,
 9,
 6,
 2,
 9,
 5,
 0,
 7,
 5,
 5,
 3,
 8,
 1,
 9,
 1,
 9,
 5,
 4,
 3,
 7,
 9,
 9,
 3,
 9,
 6,
 9,
 1,
 6,
 7,
 4,
 7,
 0,
 9,
 1,
 8,
 9,
 6,
 5,
 1,
 9,
 9,
 4,
 3,
 1,
 9,
 3,
 3,
 8,
 6,
 3,
 9,
 6,
 5,
 5,
 1,
 1,
 0,
 9,
 3,
 9,
 1,
 3,
 3,
 6,
 7,
 5,
 5,
 6,
 9,
 9,
 2,
 3,
 6,
 3,
 3,
 3,
 9,
 7,
 9,
 6,
 7,
 3,
 2,
 1,
 4,
 9,
 2,
 7,
 7,
 9,
 1,
 1,
 1,
 7,
 4,
 4,
 7,
 2,
 9,
 6,
 5,
 6,
 5,
 3,
 9,
 3,
 7,
 7,
 6,
 3,
 9,
 9,
 1,
 9,
 7,
 1,
 4,
 6,
 6,
 1,
 6,
 9,
 9,
 9,
 9,
 9,
 6,
 6,
 9,
 9,
 0,
 6,
 0,
 6,
 1,
 1,
 5,
 9,
 3,
 9,
 0,
 1,
 9,
 8,
 5,
 3,
 4,
 1,
 4,
 7,
 6,
 6,
 6,
 5,
 5,
 0,
 3,
 1,
 9,
 2,
 7,
 8,
 3,
 3,
 9,
 5,
 1,
 7,
 3,
 1,
 9,
 6,
 6,
 8,
 3,
 6,
 9,
 3,
 5,
 9,
 7,
 3,
 3,
 3,
 9,
 9,
 9,
 9,
 5,
 7,
 1,
 9,
 1,
 9,
 5,
 3,
 7,
 9,
 1,
 3,
 8,
 1,
 3,
 9,
 9,
 9,
 6,
 6,
 6,
 4,
 6,
 9,
 6,
 3,
 7,
 1,
 4,
 9,
 8,
 6,
 9,
 3,
 5,
 1,
 3,
 9,
 9,
 0,
 2,
 3,
 6,
 2,
 9,
 9,
 8,
 0,
 6,
 9,
 3,
 1,
 2,
 6,
 3,
 6,
 4,
 5,
 8,
 9,
 9,
 8,
 9,
 9,
 4,
 3,
 6,
 1,
 2,
 9,
 9,
 7,
 1,
 9,
 6,
 3,
 9,
 3,
 5,
 3,
 1,
 1,
 7,
 5,
 3,
 3,
 9,
 6,
 9,
 4,
 6,
 6,
 9,
 2,
 9,
 9,
 6,
 3,
 7,
 6,
 1,
 3,
 9,
 6,
 0,
 7,
 7,
 3,
 9,
 6,
 9,
 4,
 8,
 9,
 9,
 3,
 6,
 7,
 3,
 3,
 3,
 3,
 6,
 3,
 1,
 6,
 9,
 8,
 3,
 1,
 3,
 4,
 4,
 9,
 3,
 9,
 1,
 3,
 6,
 6,
 1,
 7,
 6,
 6,
 5,
 2,
 6,
 6,
 9,
 0,
 9,
 1,
 6,
 1,
 9,
 7,
 9,
 9,
 6,
 6,
 9,
 5,
 6,
 4,
 1,
 9,
 1,
 9,
 9,
 9,
 8,
 6,
 4,
 1,
 1,
 1,
 2,
 6,
 2,
 1,
 5,
 4,
 9,
 7,
 6,
 3,
 9,
 0,
 1,
 9,
 9,
 0,
 0,
 0,
 9,
 5,
 2,
 4,
 7,
 7,
 9,
 9,
 7,
 9,
 3,
 9,
 6,
 9,
 3,
 9,
 9,
 3,
 9,
 9,
 1,
 8,
 1,
 7,
 9,
 0,
 1,
 9,
 4,
 1,
 8,
 5,
 8,
 7,
 5,
 3,
 1,
 6,
 6,
 6,
 3,
 8,
 3,
 9,
 3,
 9,
 9,
 9,
 9,
 8,
 1,
 3,
 3,
 6,
 9,
 8,
 4,
 2,
 3,
 7,
 9,
 1,
 9,
 7,
 6,
 6,
 4,
 6,
 1,
 9,
 8,
 2,
 2,
 6,
 1,
 4,
 8,
 1,
 8,
 1,
 6,
 9,
 5,
 3,
 1,
 9,
 1,
 3,
 9,
 4,
 6,
 3,
 5,
 3,
 6,
 8,
 0,
 0,
 1,
 8,
 3,
 8,
 2,
 6,
 6,
 1,
 1,
 1,
 9,
 6,
 4,
 9,
 2,
 9,
 1,
 1,
 0,
 6,
 5,
 8,
 0,
 1,
 9,
 9,
 3,
 0,
 9,
 6,
 3,
 6,
 9,
 9,
 6,
 4,
 6,
 6,
 1,
 1,
 1,
 5,
 2,
 3,
 3,
 0,
 0,
 7,
 9,
 3,
 3,
 6,
 1,
 6,
 8,
 1,
 4,
 1,
 9,
 9,
 9,
 9,
 5,
 5,
 4,
 6,
 1,
 0,
 1,
 1,
 6,
 0,
 8,
 9,
 5,
 8,
 6,
 5,
 9,
 5,
 1,
 9,
 8,
 1,
 2,
 1,
 4,
 9,
 1,
 1,
 1,
 3,
 1,
 9,
 4,
 1,
 9,
 9,
 5,
 7,
 3,
 9,
 9,
 9,
 1,
 6,
 6,
 9,
 2,
 7,
 1,
 5,
 9,
 7,
 6,
 6,
 0,
 9,
 9,
 0,
 7,
 6,
 9,
 9,
 4,
 3,
 1,
 5,
 1,
 1,
 6,
 3,
 7,
 6,
 5,
 9,
 1,
 0,
 1,
 2,
 7,
 0,
 1,
 1,
 9,
 9,
 3,
 9,
 6,
 6,
 7,
 8,
 1,
 6,
 9,
 5,
 2,
 9,
 3,
 3,
 9,
 6,
 ...]

In [35]:
manAlldata["연령대코드(5세단위)"].head(20)

0       6
2      12
84     11
126     6
440     6
517    13
527    13
541    13
585    13
601    14
639    14
647    13
648    13
676     5
704    13
734     6
834    12
835    12
844    12
862    12
Name: 연령대코드(5세단위), dtype: int64

In [39]:
km_man = manAlldata["연령대코드(5세단위)"].tolist()

In [40]:
np.savetxt("k=10예측", km_man, delimiter=",")

In [ ]:
np.savetxt("남자나이", a, delimiter=",")

In [37]:
kmean_cl2 = KMeans(n_clusters=k2, algorithm='auto')
kmeans2 = kmean_cl2.fit(feature2)
km_predict2 = kmean_cl2.predict(feature2)
km_predict2

array([5, 6, 3, ..., 6, 7, 7])

In [41]:
km_predict2 = km_predict2.tolist()

In [ ]:
#import tensorflow as tf

In [ ]:
#vectors = tf.constant(manAlldata)

In [ ]:
#k=4

In [ ]:
#centroides = tf.Variable(tf.slice(tf.random_shuffle(vectors), [0,0], [k, -1]))

In [ ]:
#expanded_vectors = tf.expand_dims(vectors, 0)

In [ ]:
#expanded_centroides = tf.expand_dims(centroides, 1)

In [ ]:
#diff = tf.subtract(expanded_vectors, expanded_centroides)
#sqr = tf.square(diff)
#distances = tf.reduce_sum(sqr, 2)
#assignments = tf.argmin(distances, 0)

In [ ]:
#means = tf.concat([tf.reduce_mean(tf.gather(vectors, tf.reshape(tf.where(tf.equal(assignments, c)),[1,-1])),1) for c in range(k)],0)

In [ ]:
#update_centroides = tf.assign(centroides, means)

In [ ]:
#init_op = tf.global_variables_initializer()

In [ ]:
#sess = tf.Session()
#sess.run(init_op)

#num_steps=100

#for step in range(num_steps):
#    _, centroid_values, assignment_values = sess.run([update_centroides, centroides, assignments])

In [ ]:
#print(centroid_values)

In [ ]:
#print(assignment_values)